Create table salaries (
	timestamp_date TIMESTAMP NOT NULL,
	company VARCHAR(40) NOT NULL,
	level_tier VARCHAR(60) NOT NULL,
	title VARCHAR(30) NOT NULL,
	totalyearlycompensation INT NOT NULL,
	location_place VARCHAR (42) NOT NULL,
	yearsofexperience FLOAT NOT NULL,
	yearsatcompany FLOAT NOT NULL,
	tag VARCHAR(90) NOT NULL,
	basesalary INT NOT NULL,
	stockgrantvalue VARCHAR(20) NOT NULL,
	bonus FLOAT NOT NULL,
	gender VARCHAR(32) NOT NULL,
	cityid INT NOT NULL,
	dmaid INT NOT NULL,
	rowNumber INT NOT NULL,
	Masters_Degree INT NOT NULL,
	Bachelors_Degree INT NOT NULL,
	Doctorate_Degree INT NOT NULL,
	Highschool INT NOT NULL,
	Some_College INT NOT NULL,
	Race_Asian INT NOT NULL,
	Race_White INT NOT NULL,
	Race_Two_Or_More INT NOT NULL,
	Race_Black INT NOT NULL,
	Race_Hispanic INT NOT NULL,
	Race VARCHAR(12) NOT NULL,
	Education VARCHAR(18) NOT NULL,
	Primary key (rowNumber),
	Unique (rowNumber)
)